/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP DATABASE IF EXISTS `drawing-hammer`;
CREATE DATABASE IF NOT EXISTS `drawing-hammer` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `drawing-hammer`;

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password` char(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user_salt`;
CREATE TABLE IF NOT EXISTS `user_salt` (
  `userID` int(11) NOT NULL,
  `salt` varchar(70) NOT NULL,
  PRIMARY KEY (`userID`),
  CONSTRAINT `FK_user_salt_users` FOREIGN KEY (`userID`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `username`, `password`, `isBanned`) VALUES
	(1, '123456', '2AAA9630D41B3E3050EDBD899669BA48A94AB86E47ECD22CFDD5A6F868AB720D', 0),
	(2, '654321', '55D9D475B997A77DB1BEF96458BF4218AA9070A05EBC2DC167AFF13C07E21027', 0),
	(3, 'qwertz', 'D4228FBB276695171685771570B199221BE0F2AAB22D8F1FB94AC8D478CF7DDE', 0),
	(4, 'asdfgh', '3DE2BFF1C461478EDFF6495268C07B075989E8CA7C7167013F9C30949197E9A6', 0);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `user_salt` (
  `userID` int(11) NOT NULL,
  `salt` varchar(250) NOT NULL,
  PRIMARY KEY (`userID`),
  CONSTRAINT `FK_user_salt_users` FOREIGN KEY (`userID`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Exportiere Daten aus Tabelle drawing-hammer.user_salt: ~4 rows (ungefähr)
/*!40000 ALTER TABLE `user_salt` DISABLE KEYS */;
INSERT INTO `user_salt` (`userID`, `salt`) VALUES
	(1, 'VSs6Tc2hy7nceAVFiPXbQO3QA0Ox5rebGXm5PXqhUqp1eesYuUiLKsIbg6Ik0'),
	(2, 'EU9HQHTUf0kpAqRd9p3tJg3CE7GkgYIszWOMgyAhSEjfdwITfGmhRvnVUPUMXziE'),
	(3, 'saBw3S4GWXGXxoJm3Zq4gwSVnmnD7dfgttBBLy4bJU5E1SnNvUXSoFtnvGy50zcDU'),
	(4, 'cln1EiqkL0XUYK7U5k1nwcD4E4SvOby3TQldc1DZIyeAz6vViF1xoqKKH1ihWjSQ');
/*!40000 ALTER TABLE `user_salt` ENABLE KEYS */;



/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `words`;
CREATE TABLE IF NOT EXISTS `words` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `word` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE `words` DISABLE KEYS */;
INSERT INTO `words` (`word`) VALUES
	('Kaffeemaschine'),
	('Wasserwaage'),
	('Rucksack'),
	('Messerblock'),
	('Spülmaschine'),
	('Tiefgarage'),
	('Helikopter'),
	('Fußballstadion'),
	('Handy'),
	('Tastatur'),
	('Sonnenuntergang'),
	('Jahreszeiten'),
	('Nacht'),
	('Rollkragenpullover'),
	('Unterwäsche'),
	('Bus'),
	('Bahnhof'),
	('Autobahnausfahrt'),
	('Polizeikontrolle'),
	('Datenbank'),
	('Decke'),
	('Sattelitenschüssel'),
	('Salatschleuder'),
	('Kalender'),
	('Auflaufform'),
	('Serverschrank'),
	('Fernbedienung'),
	('Perrücke'),
	('Beerdigung'),
	('Geldbeutel'),
	('Monitor'),
	('Schreibtischstuhl'),
	('Einkaufswagen'),
	('Verkehrspolizist'),
	('Fahrschule'),
	('Prüfung'),
	('Arbeitsmoral'),
	('Schokonikolaus'),
	('Schlitten'),
	('Badehose'),
	('Muskelkater'),
	('Fitnessstudio'),
	('Abschlussarbeit'),
	('Wartezimmer'),
	('Zahnarztpraxis'),
	('Marathonläufer'),
	('Urlaub'),
	('Flugzeug'),
	('Spermann'),
	('Bockwurst'),
	('Polenböller'),
	('Chinakracher'),
	('Bachstelze'),
	('Zungenkuss'),
	('Mäusespeck'),
	('Trommelwirbel'),
	('Affentheater'),
	('Öl'),
	('Angelsachse'),
	('Hopfenkaltschale'),
	('Spargeltarzan'),
	('Zucker'),
	('Mehl'),
	('Hexenkessel'),
	('Sommerloch'),
	('Hüftgold'),
	('Schafspelz'),
	('Montage'),
	('Regenschauer'),
	('Wintereinbruch'),
	('Kater'),
	('Killerclown'),
	('Gurkentruppe'),
	('Blutgruppe'),
	('Darmstadt'),
	('Pausenzeichen'),
	('Unterlagsscheibe'),
	('Tabu'),
	('Wasser'),
	('Eisprung'),
	('Halsband'),
	('Hundeleine'),
	('Kirschtorte'),
	('Mädchen'),
	('Ponni'),
	('Schlagzeug'),
	('Luftschloss'),
	('Handysüchtig'),
	('Brieftaube'),
	('Spiegelei'),
	('Sex'),
	('Frosch'),
	('Alptraum'),
	('Zündschnur'),
	('Bücherwurm'),
	('Fischstäbchen'),
	('Bazille'),
	('Kettenraucher'),
	('Schlafanzug'),
	('Feldstecher'),
	('Bandit'),
	('Milchstraße'),
	('Ameisenbär'),
	('Morgenluft'),
	('Gänsehaut'),
	('Anfänger'),
	('Strohsack'),
	('Lampe'),
	('Applaudieren'),
	('Bogen'),
	('Pfeil'),
	('Schlauch'),
	('Stehen'),
	('Gespräch'),
	('Wasserträger'),
	('Ananas'),
	('Dose'),
	('Scheibe'),
	('Überquerung'),
	('Milchmädchenrechnung'),
	('Querschläger'),
	('Stunde'),
	('Minute'),
	('Sekunde'),
	('Hochprozentiges'),
	('Ochse'),
	('Berg'),
	('Blinder'),
	('Kuh'),
	('Füße'),
	('Nudeln'),
	('Rückenwind'),
	('Promi'),
	('Halbkreis'),
	('Schlußstrich'),
	('Haltelinie'),
	('Busspur'),
	('Taxischein'),
	('Rückwärtsgang'),
	('Schaltvorgang'),
	('Lösung'),
	('Eintopf'),
	('Alphabet'),
	('Rechtsträger'),
	('Linksträger'),
	('Einfädeln'),
	('Nähmaschine'),
	('Hähnchen'),
	('Wollknäuel'),
	('Sauerstoff'),
	('Verbindung'),
	('Mathematik'),
	('Giftzwerg'),
	('Bösewicht'),
	('Schwarzgeld'),
	('Seitenscheitel'),
	('Heuhaufen'),
	('Mähdrescher'),
	('Traktor'),
	('Heuballen'),
	('Stall'),
	('Korken'),
	('Bierkasten'),
	('Brauerei'),
	('Hopfen'),
	('Popcorn'),
	('Soße'),
	('Tasche'),
	('Mücken'),
	('Brust'),
	('Bauklötze'),
	('Frosch'),
	('Gras'),
	('Laufpass'),
	('Atemzug'),
	('Drehwurm'),
	('Sockenschuss'),
	('Vogel'),
	('Feuer'),
	('Spaßvogel'),
	('Mordsspaß'),
	('Stiefel'),
	('Tomaten'),
	('Rosinen'),
	('Redensart'),
	('Abwrackprämie'),
	('Brillenschlange'),
	('Lachsack'),
	('Kotflügel'),
	('Zipfelmütze'),
	('Eisprung'),
	('Schwan'),
	('Freitag'),
	('Blaskapelle'),
	('Dreieck'),
	('Kugelschreiber'),
	('Bierfahne'),
	('Fahne'),
	('Schnupftabak'),
	('Priese'),
	('Kopfsalat'),
	('Backen'),
	('Lauwarm'),
	('Zeitgeist'),
	('Schneckentempo'),
	('Kohldampf'),
	('Karton'),
	('Ruhe'),
	('Brechstange'),
	('Hummeln'),
	('Hintern'),
	('Musik'),
	('Blut'),
	('Milchsäure'),
	('Schiff'),
	('Taubstumm'),
	('Zwillinge'),
	('Schweinsgallop'),
	('Jägerschnitzel'),
	('Puffreis'),
	('Notenständer'),
	('Eierwärmer'),
	('Sauerkraut'),
	('Grünkohl'),
	('Rostlaube'),
	('Windrichtung'),
	('Hinterwäldler'),
	('Bodensee'),
	('Hauptstadt'),
	('WM'),
	('Bananenflanke'),
	('Zement'),
	('Reis'),
	('Schwitzkasten'),
	('Spiegeleier'),
	('Quadratlatschen'),
	('Bohnenstange'),
	('Bücherei'),
	('Blutgruppe'),
	('Keller'),
	('Hungertuch'),
	('Durststrecke'),
	('Blickwinkel'),
	('Affenzahn'),
	('Haarspalterei'),
	('Schaumkrone'),
	('Medizinball'),
	('Salamitaktik'),
	('Hollywoodschaukel'),
	('Schwarzfahrer'),
	('Magenbrot'),
	('Eselsbrücke'),
	('Klosterfrau'),
	('Marmorkuchen'),
	('Reißverschluss'),
	('Fegefeuer'),
	('Mottenkugeln'),
	('Staubmäuse'),
	('Landjäger'),
	('Fliegenklatsche'),
	('Lupe'),
	('Quarktasche'),
	('Nichtschwimmer'),
	('Spion'),
	('Trampelpfad'),
	('Kleinkariert'),
	('Nervensäge'),
	('Erbsenzähler'),
	('Hühnerauge'),
	('Krähenfüße'),
	('Fuchsschwanz'),
	('Dreikäsehoch'),
	('Flohmarkt'),
	('Muskelkater'),
	('Eselsohr'),
	('Affenschande'),
	('Rohrkrepierer'),
	('Blindgänger'),
	('Wasserglas'),
	('Sonnenuntergang'),
	('Kreißel'),
	('Nebel'),
	('Neunmalklug'),
	('Siebenschläfer'),
	('Kreuzworträtsel'),
	('Hausschuhen'),
	('Motivation'),
	('Schalldämpfer'),
	('Multiplikation'),
	('Gedanke'),
	('Quadratwurzel'),
	('Lampenfieber'),
	('Kurzsichtigkeit'),
	('Blähungen'),
	('Flatulenz'),
	('Bauchgefühl'),
	('Regenwahrscheinlichkeit'),
	('Seelenwärmer'),
	('Schweinehund'),
	('Seifenblase'),
	('Pferdeapfel'),
	('Kaugummi'),
	('Montagsmaler'),
	('Teenager'),
	('Inflation'),
	('Bruttosozialprodukt'),
	('Achselschweiß'),
	('Armdrücken'),
	('Bär'),
	('Arzt'),
	('Baby'),
	('Blinklicht'),
	('Boxer'),
	('Brustschwimmen'),
	('Bürgermeister'),
	('Detektiv'),
	('Dickkopf'),
	('Dirigent'),
	('Dompteur'),
	('Eisbär'),
	('Elvis'),
	('Eskimo'),
	('Fahrradkette'),
	('Fee'),
	('Federball'),
	('Flaschenhals'),
	('Gabelstapler'),
	('Herzensbrecher'),
	('Haarföhn'),
	('Indianer'),
	('Känguru'),
	('Google'),
	('Microsoft'),
	('Käsefüße'),
	('Kellnerin'),
	('Knopf'),
	('Kopfschmerzen'),
	('Matrose'),
	('Papst'),
	('Politiker'),
	('Putzfrau'),
	('Schornsteinfeger'),
	('Sonnenblume'),
	('Sumoringer'),
	('Hochhaus'),
	('Teekanne'),
	('Hundehütte'),
	('Schatzkiste'),
	('Fensterbank'),
	('Salzstange'),
	('Schubkarre'),
	('Sternenhimmel'),
	('Regenwolke'),
	('Apfelbaum'),
	('Pommes'),
	('Riesenrad'),
	('Vampir'),
	('Tausendfüßler'),
	('Bügeleisen'),
	('Glühbirne'),
	('Bonbon'),
	('Erdbeere'),
	('Autoreparatur'),
	('Folterkammer'),
	('Muskelzucken'),
	('Messerwerfer'),
	('Morgengymnastik'),
	('Pistolenduell'),
	('Sphinx'),
	('Stammhalter'),
	('Verkehrspolizist'),
	('Politesse'),
	('Feuerwehrmann'),
	('Dachterasse'),
	('Wagenheber'),
	('Zugbrücke'),
	('Ritter'),
	('Kastanienbaum'),
	('Schwertfisch'),
	('Kopfnuss'),
	('Aktenkoffer'),
	('Butterdose'),
	('Buchrücken'),
	('Buntstift'),
	('Besenkammer'),
	('Brechreiz'),
	('Wasen'),
	('Betrunken'),
	('Dirne'),
	('Dönerbude'),
	('Obstmesser'),
	('Tattoonadel'),
	('Zigaretten'),
	('Waffeleisen'),
	('Hängematte'),
	('Navigationssystem'),
	('Notfallset'),
	('Whatsapp'),
	('Insekt'),
	('Pfefferminte'),
	('Betrüger'),
	('Flüchtling'),
	('Amerika'),
	('Kontintent'),
	('Reis'),
	('Chinese'),
	('Sumoringer'),
	('Krieg'),
	('Trump'),
	('Merkel'),
	('YouTube'),
	('Porno'),
	('Marke'),
	('Droge'),
	('Abteilung'),
	('Becken'),
	('Puppe'),
	('Rosa'),
	('Schwein'),
	('Löffel'),
	('Biber'),
	('Verführer'),
	('Schmiermittel'),
	('Mutant'),
	('Kinofilm'),
	('Schalter'),
	('Höhepunkt'),
	('Schatz'),
	('Volumen'),
	('Unterkunft'),
	('Lärm'),
	('Baumwolle'),
	('Harpune'),
	('Landschaft'),
	('Raid'),
	('Bundesland'),
	('Dekadenz'),
	('Aprikose'),
	('Darstellerin'),
	('Seifenbalsen'),
	('Todesfalle'),
	('Saw'),
	('Seele'),
	('Geschirr'),
	('Fraktion'),
	('Waisenhaus'),
	('Kategorie'),
	('Krypta'),
	('Ehefrau'),
	('Versteck'),
	('Zivilisation'),
	('Tiger'),
	('Kurve'),
	('Blasrohr'),
	('Sanitäter'),
	('Notarzt'),
	('Golfball'),
	('Golfen'),
	('Tennis'),
	('Tischtennis'),
	('Ehrenamt'),
	('Schatulle'),
	('Zuhälter'),
	('Elfenbein'),
	('Medizin'),
	('Babysitter'),
	('Niederschlag'),
	('Sicherung'),
	('Code'),
	('Segen'),
	('Zement'),
	('Hügel'),
	('Zucker'),
	('Opposition'),
	('Wal'),
	('Wahl'),
	('Kreuzfahrer'),
	('Pilger'),
	('Abenteuer'),
	('Überbringer'),
	('Hexe'),
	('Gänseblümchen'),
	('Kindisch'),
	('Fohlen'),
	('Kommunikation'),
	('Rippe'),
	('Blutkreislauf'),
	('Leitplanke'),
	('Bausstellenschild'),
	('Umleitung'),
	('Umfahrung'),
	('Dynamit'),
	('Rüstung'),
	('Mana'),
	('Ozean'),
	('Kätzchen'),
	('Flughafen'),
	('Absturz'),
	('Teehaus'),
	('Delikatesse');
	
	
		
/*!40000 ALTER TABLE `words` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;


/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
